# prompt.yml
# Template for code generation prompts

prompts:
  - name: Create Angular Component
    description: Generate a new Angular component with example features
    example:
      request: "Create a new Angular component named 'UserProfile' with input properties for 'user', output event 'profileUpdated', and a template displaying user info."
      response: |
        ng generate component user-profile
        // Add @Input() user, @Output() profileUpdated, and template code
  # Add more prompt templates below
