-- ============================================================
-- board_lists: list containers that exist inside a board
-- ============================================================
CREATE TABLE public.board_lists (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id   bigint NOT NULL REFERENCES public.boards(id) ON DELETE CASCADE,
  name       character varying NOT NULL,
  position   smallint NOT NULL DEFAULT 0,
  user_id    uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.board_lists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own board lists"
  ON public.board_lists FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own board lists"
  ON public.board_lists FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own board lists"
  ON public.board_lists FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own board lists"
  ON public.board_lists FOR DELETE
  USING (auth.uid() = user_id);
