-- ============================================================
-- Board Collaboration: tables, types, helper function, and RLS
-- ============================================================

-- 1. Custom enum for collaboration roles
CREATE TYPE public.collaborator_role AS ENUM ('owner', 'editor', 'viewer');

-- 2. Custom enum for invitation status
CREATE TYPE public.invitation_status AS ENUM ('pending', 'accepted', 'declined');

-- ============================================================
-- board_collaborators: bridging table linking boards to users
-- ============================================================
CREATE TABLE public.board_collaborators (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id    bigint NOT NULL REFERENCES public.boards(id) ON DELETE CASCADE,
  user_id     uuid   NOT NULL REFERENCES auth.users(id)    ON DELETE CASCADE,
  role        public.collaborator_role NOT NULL DEFAULT 'viewer',
  invited_by  uuid   REFERENCES auth.users(id) ON DELETE SET NULL,
  status      public.invitation_status NOT NULL DEFAULT 'pending',
  created_at  timestamptz NOT NULL DEFAULT now(),
  accepted_at timestamptz,
  UNIQUE (board_id, user_id)
);

CREATE INDEX idx_board_collaborators_board_id ON public.board_collaborators (board_id);
CREATE INDEX idx_board_collaborators_user_id  ON public.board_collaborators (user_id);

-- ============================================================
-- board_invitations: tracks invitations sent by email
-- (supports inviting users who may not have an account yet)
-- ============================================================
CREATE TABLE public.board_invitations (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id    bigint NOT NULL REFERENCES public.boards(id) ON DELETE CASCADE,
  email       character varying(255) NOT NULL,
  role        public.collaborator_role NOT NULL DEFAULT 'viewer',
  invited_by  uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token       uuid   NOT NULL DEFAULT gen_random_uuid(),
  created_at  timestamptz NOT NULL DEFAULT now(),
  expires_at  timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  UNIQUE (board_id, email)
);

CREATE INDEX idx_board_invitations_board_id ON public.board_invitations (board_id);
CREATE INDEX idx_board_invitations_email    ON public.board_invitations (email);
CREATE INDEX idx_board_invitations_token    ON public.board_invitations (token);

-- ============================================================
-- Helper function: check if the current user is the board owner
-- or an accepted collaborator with at least the given role.
-- Role hierarchy: owner > editor > viewer
-- ============================================================
CREATE OR REPLACE FUNCTION public.has_board_access(
  p_board_id bigint,
  p_min_role public.collaborator_role DEFAULT 'viewer'
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    -- Board owner always has access
    SELECT 1 FROM public.boards b
    WHERE b.id = p_board_id AND b.user_id = auth.uid()
  )
  OR EXISTS (
    SELECT 1 FROM public.board_collaborators bc
    WHERE bc.board_id = p_board_id
      AND bc.user_id  = auth.uid()
      AND bc.status   = 'accepted'
      AND CASE p_min_role
            WHEN 'viewer' THEN bc.role IN ('viewer', 'editor', 'owner')
            WHEN 'editor' THEN bc.role IN ('editor', 'owner')
            WHEN 'owner'  THEN bc.role = 'owner'
          END
  );
$$;

-- ============================================================
-- RLS for board_collaborators
-- ============================================================
ALTER TABLE public.board_collaborators ENABLE ROW LEVEL SECURITY;

-- Board owners can see all collaborators on their boards
CREATE POLICY "Board owners can view collaborators"
  ON public.board_collaborators FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.boards b
      WHERE b.id = board_id AND b.user_id = auth.uid()
    )
    OR user_id = auth.uid()
  );

-- Only board owners can invite collaborators
CREATE POLICY "Board owners can insert collaborators"
  ON public.board_collaborators FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.boards b
      WHERE b.id = board_id AND b.user_id = auth.uid()
    )
  );

-- Board owners can update collaborator roles; collaborators can accept/decline
CREATE POLICY "Board owners and invitees can update collaborators"
  ON public.board_collaborators FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.boards b
      WHERE b.id = board_id AND b.user_id = auth.uid()
    )
    OR user_id = auth.uid()
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.boards b
      WHERE b.id = board_id AND b.user_id = auth.uid()
    )
    OR user_id = auth.uid()
  );

-- Only board owners can remove collaborators
CREATE POLICY "Board owners can delete collaborators"
  ON public.board_collaborators FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.boards b
      WHERE b.id = board_id AND b.user_id = auth.uid()
    )
    OR user_id = auth.uid()
  );

-- ============================================================
-- RLS for board_invitations
-- ============================================================
ALTER TABLE public.board_invitations ENABLE ROW LEVEL SECURITY;

-- Board owners can see invitations they sent
CREATE POLICY "Board owners can view invitations"
  ON public.board_invitations FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.boards b
      WHERE b.id = board_id AND b.user_id = auth.uid()
    )
  );

-- Only board owners can create invitations
CREATE POLICY "Board owners can insert invitations"
  ON public.board_invitations FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.boards b
      WHERE b.id = board_id AND b.user_id = auth.uid()
    )
  );

-- Board owners can update invitations (e.g. resend / change role)
CREATE POLICY "Board owners can update invitations"
  ON public.board_invitations FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.boards b
      WHERE b.id = board_id AND b.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.boards b
      WHERE b.id = board_id AND b.user_id = auth.uid()
    )
  );

-- Board owners can delete/revoke invitations
CREATE POLICY "Board owners can delete invitations"
  ON public.board_invitations FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.boards b
      WHERE b.id = board_id AND b.user_id = auth.uid()
    )
  );

-- ============================================================
-- Updated RLS policies on existing tables to allow collaborators
-- ============================================================

-- ---- boards ----
-- Allow collaborators to SELECT shared boards
CREATE POLICY "Collaborators can view shared boards"
  ON public.boards FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.board_collaborators bc
      WHERE bc.board_id = id
        AND bc.user_id  = auth.uid()
        AND bc.status   = 'accepted'
    )
  );

-- Allow editor/owner collaborators to UPDATE shared boards
CREATE POLICY "Collaborators can update shared boards"
  ON public.boards FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.board_collaborators bc
      WHERE bc.board_id = id
        AND bc.user_id  = auth.uid()
        AND bc.status   = 'accepted'
        AND bc.role IN ('editor', 'owner')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.board_collaborators bc
      WHERE bc.board_id = id
        AND bc.user_id  = auth.uid()
        AND bc.status   = 'accepted'
        AND bc.role IN ('editor', 'owner')
    )
  );

-- ---- board_lists ----
-- Allow collaborators to view lists on shared boards
CREATE POLICY "Collaborators can view shared board lists"
  ON public.board_lists FOR SELECT
  USING (
    public.has_board_access(board_id, 'viewer')
  );

-- Allow editor collaborators to insert lists on shared boards
CREATE POLICY "Collaborators can insert shared board lists"
  ON public.board_lists FOR INSERT
  WITH CHECK (
    public.has_board_access(board_id, 'editor')
  );

-- Allow editor collaborators to update lists on shared boards
CREATE POLICY "Collaborators can update shared board lists"
  ON public.board_lists FOR UPDATE
  USING (
    public.has_board_access(board_id, 'editor')
  );

-- Allow editor collaborators to delete lists on shared boards
CREATE POLICY "Collaborators can delete shared board lists"
  ON public.board_lists FOR DELETE
  USING (
    public.has_board_access(board_id, 'editor')
  );

-- ---- tasks ----
-- Allow collaborators to view tasks on shared boards
CREATE POLICY "Collaborators can view shared board tasks"
  ON public.tasks FOR SELECT
  USING (
    board_id IS NOT NULL
    AND public.has_board_access(board_id, 'viewer')
  );

-- Allow editor collaborators to insert tasks on shared boards
CREATE POLICY "Collaborators can insert shared board tasks"
  ON public.tasks FOR INSERT
  WITH CHECK (
    board_id IS NOT NULL
    AND public.has_board_access(board_id, 'editor')
  );

-- Allow editor collaborators to update tasks on shared boards
CREATE POLICY "Collaborators can update shared board tasks"
  ON public.tasks FOR UPDATE
  USING (
    board_id IS NOT NULL
    AND public.has_board_access(board_id, 'editor')
  );

-- Allow editor collaborators to delete tasks on shared boards
CREATE POLICY "Collaborators can delete shared board tasks"
  ON public.tasks FOR DELETE
  USING (
    board_id IS NOT NULL
    AND public.has_board_access(board_id, 'editor')
  );

-- ---- activities ----
-- Collaborators can view activities linked to shared board tasks
CREATE POLICY "Collaborators can view shared board activities"
  ON public.activities FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.task_activities ta
      JOIN public.tasks t ON t.id = ta.task_id
      WHERE ta.activity_id = activities.id
        AND t.board_id IS NOT NULL
        AND public.has_board_access(t.board_id, 'viewer')
    )
  );

-- Collaborators can insert activities for shared board tasks
CREATE POLICY "Collaborators can insert shared board activities"
  ON public.activities FOR INSERT
  WITH CHECK (
    auth.uid() IS NOT NULL
  );

-- Collaborators can update activities linked to shared board tasks
CREATE POLICY "Collaborators can update shared board activities"
  ON public.activities FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.task_activities ta
      JOIN public.tasks t ON t.id = ta.task_id
      WHERE ta.activity_id = activities.id
        AND t.board_id IS NOT NULL
        AND public.has_board_access(t.board_id, 'editor')
    )
  );

-- Collaborators can delete activities linked to shared board tasks
CREATE POLICY "Collaborators can delete shared board activities"
  ON public.activities FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.task_activities ta
      JOIN public.tasks t ON t.id = ta.task_id
      WHERE ta.activity_id = activities.id
        AND t.board_id IS NOT NULL
        AND public.has_board_access(t.board_id, 'editor')
    )
  );

-- ---- task_activities ----
-- Collaborators can view task_activities for shared board tasks
CREATE POLICY "Collaborators can view shared board task activities"
  ON public.task_activities FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.tasks t
      WHERE t.id = task_id
        AND t.board_id IS NOT NULL
        AND public.has_board_access(t.board_id, 'viewer')
    )
  );

-- Collaborators can insert task_activities for shared board tasks
CREATE POLICY "Collaborators can insert shared board task activities"
  ON public.task_activities FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.tasks t
      WHERE t.id = task_id
        AND t.board_id IS NOT NULL
        AND public.has_board_access(t.board_id, 'editor')
    )
  );

-- Collaborators can update task_activities for shared board tasks
CREATE POLICY "Collaborators can update shared board task activities"
  ON public.task_activities FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.tasks t
      WHERE t.id = task_id
        AND t.board_id IS NOT NULL
        AND public.has_board_access(t.board_id, 'editor')
    )
  );

-- Collaborators can delete task_activities for shared board tasks
CREATE POLICY "Collaborators can delete shared board task activities"
  ON public.task_activities FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.tasks t
      WHERE t.id = task_id
        AND t.board_id IS NOT NULL
        AND public.has_board_access(t.board_id, 'editor')
    )
  );

-- ============================================================
-- RPC: Accept a board invitation (token-based)
-- Validates the token, creates a board_collaborator record,
-- and deletes the invitation in a single transaction.
-- ============================================================
CREATE OR REPLACE FUNCTION public.accept_board_invitation(p_token uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_invitation record;
  v_collaborator_id bigint;
BEGIN
  -- Find the invitation
  SELECT * INTO v_invitation
  FROM public.board_invitations
  WHERE token = p_token
    AND expires_at > now();

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invitation not found or expired');
  END IF;

  -- Upsert into board_collaborators
  INSERT INTO public.board_collaborators (board_id, user_id, role, invited_by, status, accepted_at)
  VALUES (v_invitation.board_id, auth.uid(), v_invitation.role, v_invitation.invited_by, 'accepted', now())
  ON CONFLICT (board_id, user_id)
  DO UPDATE SET
    role        = EXCLUDED.role,
    status      = 'accepted',
    accepted_at = now()
  RETURNING id INTO v_collaborator_id;

  -- Remove the invitation
  DELETE FROM public.board_invitations WHERE id = v_invitation.id;

  RETURN jsonb_build_object(
    'success', true,
    'collaborator_id', v_collaborator_id,
    'board_id', v_invitation.board_id
  );
END;
$$;
