-- ============================================================
-- board_templates: global (system) or user-created board blueprints
-- ============================================================
CREATE TABLE public.board_templates (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        character varying NOT NULL,
  description text,
  is_system   boolean NOT NULL DEFAULT false,
  user_id     uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- board_template_lists: named list slots belonging to a template
-- list_type maps to IdeaType enum:
--   0 = ideas | 1 = goals | 2 = objectives | 3 = achievements | 4 = symptoms
-- ============================================================
CREATE TABLE public.board_template_lists (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id  bigint NOT NULL REFERENCES public.board_templates(id) ON DELETE CASCADE,
  name         character varying NOT NULL,
  list_type    smallint,
  position     smallint NOT NULL DEFAULT 0
);

-- ============================================================
-- board_template_tasks: default tasks seeded into a board from a template
-- ============================================================
CREATE TABLE public.board_template_tasks (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id      bigint NOT NULL REFERENCES public.board_templates(id)      ON DELETE CASCADE,
  template_list_id bigint NOT NULL REFERENCES public.board_template_lists(id) ON DELETE CASCADE,
  name             character varying NOT NULL,
  description      text,
  position         smallint NOT NULL DEFAULT 0
);

-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE public.board_templates      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_template_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_template_tasks ENABLE ROW LEVEL SECURITY;

-- board_templates: system templates visible to all authenticated users; user templates to owner only
CREATE POLICY "Read system or own templates"
  ON public.board_templates FOR SELECT
  USING (is_system = true OR auth.uid() = user_id);

CREATE POLICY "Insert own templates"
  ON public.board_templates FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Update own templates"
  ON public.board_templates FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Delete own templates"
  ON public.board_templates FOR DELETE
  USING (auth.uid() = user_id);

-- board_template_lists: inherit visibility via parent template
CREATE POLICY "Read lists of visible templates"
  ON public.board_template_lists FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.board_templates t
      WHERE t.id = template_id AND (t.is_system = true OR t.user_id = auth.uid())
    )
  );

CREATE POLICY "Manage lists of own templates"
  ON public.board_template_lists FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.board_templates t
      WHERE t.id = template_id AND t.user_id = auth.uid()
    )
  );

-- board_template_tasks: inherit visibility via parent template
CREATE POLICY "Read tasks of visible templates"
  ON public.board_template_tasks FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.board_templates t
      WHERE t.id = template_id AND (t.is_system = true OR t.user_id = auth.uid())
    )
  );

CREATE POLICY "Manage tasks of own templates"
  ON public.board_template_tasks FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.board_templates t
      WHERE t.id = template_id AND t.user_id = auth.uid()
    )
  );

-- ============================================================
-- Seed: Counter Endometriosis (system template)
-- ============================================================
WITH tmpl AS (
  INSERT INTO public.board_templates (name, description, is_system)
  VALUES (
    'Counter Endometriosis',
    'A structured board to help track and manage endometriosis — covering symptoms, preventive measures, diet & exercise, and personal notes.',
    true
  )
  RETURNING id
),
lists AS (
  INSERT INTO public.board_template_lists (template_id, name, list_type, position)
  SELECT tmpl.id, v.name, v.list_type, v.position
  FROM tmpl, (VALUES
    ('Symptoms',            4, 0),
    ('Preventive Measures', 1, 1),
    ('Diet & Exercise',     2, 2),
    ('Other Notes',         3, 3)
  ) AS v(name, list_type, position)
  RETURNING id, list_type, template_id
)
INSERT INTO public.board_template_tasks (template_id, template_list_id, name, description, position)
SELECT
  l.template_id,
  l.id,
  t.name,
  t.description,
  t.position
FROM lists l
JOIN (VALUES
  -- Symptoms (list_type = 4)
  (4, 'Chronic pelvic pain (especially during menstruation)',  'One of the most common symptoms. Record intensity (1–10), duration, and when it occurs in your cycle.', 0),
  (4, 'Heavy or irregular menstrual bleeding',                 'Note flow volume, duration, and any changes compared to previous cycles.', 1),
  (4, 'Pain during or after sexual intercourse (dyspareunia)', 'Track frequency and severity. Discuss with your gynaecologist if persistent.', 2),
  (4, 'Pain with bowel movements or urination',                'Particularly common during menstruation. Log occurrence dates and severity.', 3),
  (4, 'Abdominal bloating and nausea',                         'Note relation to menstrual cycle, foods eaten, and any triggers identified.', 4),
  (4, 'Persistent fatigue and low energy',                     'Rate energy levels daily and track correlation with cycle phases.', 5),
  (4, 'Lower back and leg pain',                               'Document location, intensity, and timing. Note any relief measures that help.', 6),
  (4, 'Infertility or difficulty conceiving',                  'Endometriosis affects up to 50% of women with infertility. Seek specialist advice early.', 7),
  -- Preventive Measures (list_type = 1 = goals)
  (1, 'Track menstrual cycle and symptoms daily',              'Use a diary or app to log pain levels, flow, mood, and other symptoms each day.', 0),
  (1, 'Schedule regular gynaecological check-ups',             'Aim for at least one appointment every 6–12 months, or as advised by your doctor.', 1),
  (1, 'Discuss hormonal management with your doctor',          'Hormonal therapies (e.g., combined oral contraceptives, progestins, GnRH analogues) can reduce lesion activity and pain.', 2),
  (1, 'Practice stress-reduction techniques',                  'Mindfulness, meditation, and deep breathing exercises can help lower cortisol and reduce inflammation.', 3),
  (1, 'Maintain a healthy body weight',                        'Excess body fat can increase oestrogen levels, potentially worsening endometriosis.', 4),
  (1, 'Avoid inflammatory foods',                              'Minimise trans fats, processed foods, and red meat which can promote inflammation.', 5),
  (1, 'Seek early medical attention for unusual symptoms',     'Early diagnosis and treatment can help slow disease progression and preserve fertility.', 6),
  (1, 'Connect with a support group',                          'Peer support can improve emotional wellbeing. Look for local or online endometriosis communities.', 7),
  -- Diet & Exercise (list_type = 2 = objectives)
  (2, 'Eat anti-inflammatory foods daily',                     'Include fatty fish (salmon, mackerel), berries, leafy greens, turmeric, and ginger in your meals.', 0),
  (2, 'Increase fibre intake',                                 'Aim for 25–35 g/day from vegetables, legumes, and whole grains to support gut health and oestrogen clearance.', 1),
  (2, 'Reduce red meat and processed foods',                   'Studies link high red meat consumption to increased endometriosis risk. Substitute with plant proteins and fish.', 2),
  (2, 'Limit caffeine and alcohol',                            'Both can increase oestrogen levels and worsen inflammation. Aim for fewer than 1 caffeinated drink per day.', 3),
  (2, 'Stay hydrated (8–10 glasses of water daily)',           'Adequate hydration supports detoxification and reduces bloating.', 4),
  (2, 'Practise gentle yoga and stretching',                   'Yoga poses targeting the hips and pelvis can relieve pain and improve flexibility. Aim for 3x per week.', 5),
  (2, 'Low-impact cardio exercise',                            'Walking, swimming, or cycling for 30 minutes/day helps reduce oestrogen, ease pain, and improve mood.', 6),
  (2, 'Supplement with omega-3 fatty acids',                   'Omega-3s (fish oil) have anti-inflammatory effects that may reduce endometriosis-related pain. Consult your doctor before starting.', 7),
  -- Other Notes (list_type = 3 = achievements)
  (3, 'Daily pain level log',                                  'Rate pain on a scale of 1–10 each day. Note location, duration, and any relief measures used.', 0),
  (3, 'Medication and supplement tracker',                     'Record all medications, supplements, dosages, and any side effects experienced.', 1),
  (3, 'Medical appointments diary',                            'Log appointment dates, doctors seen, diagnoses, and recommended next steps.', 2),
  (3, 'Healthcare provider contact list',                      'Keep a list of your gynaecologist, GP, specialist, and emergency contacts with phone numbers.', 3),
  (3, 'Symptom trigger journal',                               'Identify and record foods, activities, stress events, or environmental factors that worsen symptoms.', 4),
  (3, 'Mental health and emotional wellbeing notes',           'Track mood, anxiety, and emotional state daily. Note any correlation with physical symptoms or cycle phases.', 5),
  (3, 'Emergency contacts and care plan',                      'Document who to call in a pain crisis, your preferred hospital, and your current treatment plan summary.', 6)
) AS t(list_type, name, description, position) ON l.list_type = t.list_type;
