-- ============================================================
-- activities: flexible activity definitions with JSON data & media
-- ============================================================
CREATE TABLE public.activities (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       character varying NOT NULL,
  data       jsonb DEFAULT '[]'::jsonb,
  media      jsonb DEFAULT '[]'::jsonb,
  user_id    uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- task_activities: bridge between tasks and activities (max 20 per task)
-- ============================================================
CREATE TABLE public.task_activities (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id     bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  activity_id bigint NOT NULL REFERENCES public.activities(id) ON DELETE CASCADE,
  position    smallint NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (task_id, activity_id)
);

-- ============================================================
-- Trigger function: enforce max 20 activities per task
-- ============================================================
CREATE OR REPLACE FUNCTION public.check_task_activities_limit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF (
    SELECT count(*) FROM public.task_activities WHERE task_id = NEW.task_id
  ) >= 20 THEN
    RAISE EXCEPTION 'A task can have a maximum of 20 activities';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_task_activities_limit
  BEFORE INSERT OR UPDATE OF task_id ON public.task_activities
  FOR EACH ROW
  EXECUTE FUNCTION public.check_task_activities_limit();

-- ============================================================
-- RLS
-- ============================================================
ALTER TABLE public.activities       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_activities  ENABLE ROW LEVEL SECURITY;

-- activities: users can manage their own activities
CREATE POLICY "Users can view their own activities"
  ON public.activities FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own activities"
  ON public.activities FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own activities"
  ON public.activities FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own activities"
  ON public.activities FOR DELETE
  USING (auth.uid() = user_id);

-- task_activities: inherit access via the parent task owner
CREATE POLICY "Users can view their own task activities"
  ON public.task_activities FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.tasks t
      WHERE t.id = task_id AND t.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert their own task activities"
  ON public.task_activities FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.tasks t
      WHERE t.id = task_id AND t.user_id = auth.uid()
    )
    AND EXISTS (
      SELECT 1 FROM public.activities a
      WHERE a.id = activity_id AND a.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update their own task activities"
  ON public.task_activities FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.tasks t
      WHERE t.id = task_id AND t.user_id = auth.uid()
    )
    AND EXISTS (
      SELECT 1 FROM public.activities a
      WHERE a.id = activity_id AND a.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can delete their own task activities"
  ON public.task_activities FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.tasks t
      WHERE t.id = task_id AND t.user_id = auth.uid()
    )
  );

-- ============================================================
-- Indexes for common queries
-- ============================================================
CREATE INDEX idx_activities_user_id ON public.activities (user_id);
CREATE INDEX idx_task_activities_task_id ON public.task_activities (task_id);
CREATE INDEX idx_task_activities_activity_id ON public.task_activities (activity_id);
