name: Build on Push

on:
  push:
    branches:
      - live # Triggers the workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Use the node version required for your project

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
